### ISSUE TITLE
Loads of lyrics - How to contribute?

### ISSUE THREAD

**Issue by vanita5** [Lyrics/lyrics#11]
I'd like to contribute with my collection of lyrics.

As you state in your README:

> Fork the repository.
> **Use a branch named after the artist (all lowercase, dashes-instead-of-spaces).**
> Make a PR.
> Wait for some good karma.

Now, I have a collection of lyrics for about 2000-3000 and it would be pretty annoying to create seperate branches and pull requests for all of them. Would you be okay with a single big pull request?

**Comment by vflyson** [comment]
Hello @vanita5 
First of all, I'd like to apologize for such a late reply, I have no idea how I managed overlook this open issue.

In case of a big contribution, especially during this early stage of the project, I believe it'd be logical to skip the branching part and merge in bulk.
I actually never thought about the case when people would like to merge in their local collections.
Please feel free to make a PR. I will go over the texts and merge your collection into the database.

Meanwhile will figure out how to improve the instructions to simplify the contribution process.

Once again, sorry for the late reply and thank you for such a big contribution.

**Comment by vflyson** [comment]
I will close this issue now.
Please feel free to make your PR, I'll follow reviewing it and then we'll merge your lyrics into the public database.
Thank you.
