### ISSUE TITLE
Text files should have a "Language" metadata attribute

### ISSUE THREAD

**Issue by vflyson** [Lyrics/lyrics#227]
In order to make it possible to search lyrics by language, every non-instrumental file should feature a property which indicates the language of the text, possibly an array, e.g.
```
Language  en_US,  de_DE
```

**Comment by C0rn3j** [comment]
For search I'd really make it an array, since foreign songs love putting bits and pieces of english into them. 

```
I am calling, calling now, spirits rise and falling
Собой остаться дольше...
Calling, calling, in the depth of longing
Собой остаться дольше...
```

Maybe have the first member of the array be the 'main' language and rest could be treated as additives, so you could possibly filter them out in a search?

**Comment by vflyson** [comment]
I think that sorting them may not always be obvious, e.g. unique vs. total amount of words in different languages may shift priorities around, but generally I'd say that putting the primary language first would make the most sense, at the same time I don't think we should bet too much on this rule as it may be tricky or nearly impossible to apply precise calculations to poetry. As long as all the relevant languages are mentioned within the metadata, I believe that should be good enough for this metadata property.

**Comment by vflyson** [comment]
Good point, maybe it should be "American", "Deutsch", "Romanized" then? Alternatively, we could pick the one we like the most from here 
https://en.m.wikipedia.org/wiki/Language_code

**Comment by vflyson** [comment]
This will likely be discussed further once we have more texts with the `Language  ` metadata attribute, closing the issue for now.
