### ISSUE TITLE
Define the data formats and clean up the wiki

### ISSUE THREAD

**Issue by C0rn3j** [Lyrics/lyrics#228]
[Format](https://github.com/Lyrics/lyrics/wiki/Format) page at the moment contains things that are more fit for [Contributing](https://github.com/Lyrics/lyrics/wiki/Contributing), which should be merged and 

Format should instead have actual data format stuff when that is decided upon

**Comment by C0rn3j** [comment]
@vflyson I've added a bunch of info, specifically about metadata to the format page.
https://github.com/Lyrics/lyrics/wiki/Format

Would you fill in what I missed?
Also `MBID` isn't immediately obvious, maybe change it to what LyricWiki uses - `musicbrainz`?

```
{{CreditBox
|writer   = {{wpi|Max Martin}}, {{wpi|Savan Kotecha}}, {{wpi|Alexander Kronlund}}, {{wpi|Ilya Salmanzadeh|Ilya}}, Ariana Grande
|producer = Max Martin, Ilya
}}

{{SongFooter
|fLetter     = I
|asin        = B01FRF0RU0
|iTunes      = 1091145606?i=1091145643
|allmusic    = mt0053179721
|musicbrainz = be1462c8-ce31-4caf-ba4f-cdae1ace73ea
|spotify     = 7yHEDfrJNd0zWOfXwydNH0
}}
```

**Comment by vflyson** [comment]
Thank you for updating the wiki @C0rn3j 

I think using ``` would work better on that page for example snippets, since the `inline` monospace formatting seems to compact whitespaces, while block code selection preserves them.

MBID could even be

    MusicBrainz ID  be1462c8-ce31-4caf-ba4f-cdae1ace73ea

LMML can be pretty verbose this way, especially when it gets rendered with a single space (e.g. within HTML documents). The only thing is that MusicBrainz IDs can be for albums, artists, and recordings, and perhaps if we see one within a lyrics file it's more or less obvious it's that recording's ID, but still thinking if we should specify which ID it is (e.g. https://musicbrainz.org/release/4d19c701-4383-4da7-9db4-91807334a879 has "release" in the URL, ergo just having an ID is not enough to generate proper reference to their database, but at the same time I can't think of a case where we wouldn't know where the ID's from... so perhaps "MusicBrainz ID" should be enough, and "MusicBrainz Recording ID" or "MusicBrainz Album ID" may be too excessive).

About featured artists: I'm thinking now that the metadata part may have to be redesigned, perhaps with accent on MusicBrainz for whatever is possible to refer to that database, e.g. if one would like to go through the lyrics.git database right now looking for all lyrics written by a certain artist/lyricist, they would have to search by their name (using `grep` or something like that), and it may be quite inaccurate and tedious, especially if the artist have changed their name or used different spelling at different times). Tying every artist name to a MusicBrainz ID may help, but it needs to be designed in a way that would not make the metadata section hard to read (possibly having a metadata-for-metadata section underneath, containing MusicBrainz IDs for publishing companies, writers' names, album and artist, etc).

**Comment by C0rn3j** [comment]
Was wondering why it's eating my whitespaces. Fixed.

**Comment by vflyson** [comment]
I think we don't need to have an example song as the database is full of files and it's easy to find an example file, maybe we should rather provide a small snippet which indicates the structure? E.g. something like:
```
Lyrics go here

_______________
Name  Song Name
Artist  Some Artist
Album  Album Name
Track no  10
Year  1999
Genre  Metal,  Alternative
Language  en_US,  de_DE
```

**Comment by C0rn3j** [comment]
Maybe we should provide a copy paste template similar to the one you just posted?

**Comment by vflyson** [comment]
I personally think it's a good idea to have a template, perhaps we could even combine it with automated tests to ensure that metadata is consistent across all files.

**Comment by snshn** [comment]
[Here](https://github.com/Lyrics/lyrics/blob/master/tests/database-tests.d/4-metadata.py#L12)'s something like the aforementioned metadata consistency test
