### ISSUE TITLE
Any graphics needed?

### ISSUE THREAD

**Issue by andy5995** [Lyrics/lyrics#482]
I've been playing around with gimp lately and wanted to ask if any graphics are needed for this project. If so, now or in the future, let me know.

**Comment by snshn** [comment]
Hey Andy,

thank you for offering more of your help! Currently the website is designed to be as fast and lightweight as possible, and there's a vector logo that seems to be enough to give it identity on the Internet (favicon, Twitter, etc). I'd like to take you up on your offer later if you'll still have time to design something for the project when needed later.

**Comment by andy5995** [comment]
Sure, just give me a ping and I'll let you know if I'm available at the time
