### ISSUE TITLE
Handling of filenames containing reserved chars

### ISSUE THREAD

**Issue by andy5995** [Lyrics/lyrics#543]
Maybe percent-encoding per [RFC3986](https://tools.ietf.org/html/rfc3986) could be implemented to have a consistent spec to deal with colons, etc (#542)

[How to escape (percent-encode) a URL with Python](https://www.saltycrane.com/blog/2008/10/how-escape-percent-encode-url-python/)

[https://stackoverflow.com/questions/8136788/decode-escaped-characters-in-url](https://stackoverflow.com/questions/8136788/decode-escaped-characters-in-url)

**Comment by snshn** [comment]
The main issue here is that on Windows the filesystem itself does not permit `:`, and putting percent-encoded bytes into filenames would affect the readability, hence make it much it less convenient to browse the database locally.
![](https://cdn.windowsreport.com/wp-content/uploads/2020/04/characters.png)
