### ISSUE TITLE
add credits to every text in the database

### ISSUE THREAD

**Issue by vflyson** [Lyrics/lyrics#64]
The tricky part is to find out who exactly wrote those songs and currently owns the rights.

Also, which texts inside the collection are correct to the point where it would not be an insult to the author to mention their names under those lyrics.

exmaple:
```

___________________________________________
Artist: A.B. Cdefgh
Copyright: 2010 Label, Inc.
```

**Comment by C0rn3j** [comment]
What's the point in tracking who owns the rights?  Isn't that just a needless maintenance burden?

**Comment by vflyson** [comment]
It lowers the chance of this project being shut down. It's decentralized, so shutting it down won't undo the progress, but I'd still rather it to be accessible to the public, since the goal is to just give a good source for lyrics to the world, would be a downturn for it to end up on Tor or shared as a zip file on some Discord channel.

One of the beauties of LMML is that `Written by  Author Name,  Another Author` and `Copyright  Some Publishing Company, LLC,  Another Company, Inc.` can be both parsed by scripts and computer programs, and serve as a readable statement which is valid as a legal statement, to protect the project and future of every file.
